### ISSUE TITLE
Notes Disappeared

### ISSUE THREAD

**Issue by ColetteDiskette** [muerwre/markdown-home-tab#2]
It seems there was an update recently and all of my notes have been wiped. I really hope there's a way I can get them back.

I'm using Librewolf 130.0.1-1 on Arch Linux.

**Comment by ColetteDiskette** [comment]
Found them under `./storage/default/moz-extension+++890c6ad7-3d04-40d7-9431-39e8a0c3d733/ls` (from the profile directory.)

I'm guessing the update to add note syncing isn't copying the notes over perhaps?

EDIT: My solution was to downgrade, have the older version parse the notes, and move them into local md files. I've uninstalled the extension, which is a shame, but honestly this scare pushed me away. If you have any questions about my setup that may help you diagnose what happened to me specifically, I am still willing to answer them although I'm no longer using the extension.

**Comment by muerwre** [comment]
Yeah, sorry, I introduced sync storage, which should store notes in FF account (instead of putting them in local storage), but it doesn't work properly for some reason even if I use fallback to local storage.

Will do something like other extenstions do: store localy and send it with a sync.

**Comment by atomGit** [comment]
sync being optional i hope - not everybody has or wants a FF account

**Comment by muerwre** [comment]
@atomGit @ColetteDiskette 

I'll make sync optional and running in background. Will test it for backwards compatability and push new version after 9 Oct, so you'll have time to backup your data.

**Please, backup your data.**

To restore previously lost content try doing this:

- Open new tab
- Press F12 in it
- Find 'Storage' tab in inspector
- There should be 'Local Storage' submenu
- Look for keys starting with `MarkdownEditorContainer` in it

Please, return with a feedback, if it helped.

I've honestly thought there was only me using this extension, bc Mozilla shows 1 active user.

**Comment by atomGit** [comment]
thanks @muerwre

> I've honestly thought there was only me using this extension, bc Mozilla shows 1 active user.

i don't install directly from AMO - i download extensions first and install locally - i imagine some others may do the same - i also [kill much of the telemetry](https://github.com/arkenfox/user.js) that FF collects, so maybe that's another reason why only 1 user is shown

i don't think people realize how incredibly useful it is to have a tab with notes (bookmarks, code, notes, lists, etc.) - i've been using another ext. for several years that's long gone from AMO and so i was excited to see yours pop up - with the ability to easily add columns/rows, MD support and a more polished UI, yours is even better than the one i had been using ... so again, THANKS for this

**Comment by muerwre** [comment]
Yeah, I created this extension after facing this issue: https://github.com/plibither8/markdown-new-tab/issues/54 and I think we'are talking about the same extension.

Can you tell me how you want sync to be disabled? I haven't thought about that before, but maybe there should be checkbox in settings for it (enabled by default) and button to erase sync data.

Also, feel free to create feature requests here, not only that gives me ideas, but also motivates alot.

**Comment by atomGit** [comment]
the one i'm using is Mark-It - no longer on AMO

regarding sync, i personally don't use it (i like to have control over my own data), so i'd prefer to have it completely disabled via an option in settings as you mentioned and i would suggest that it be disabled by default - that seems to be the de-facto standard among extensions that use it, plus us privacy folks prefer opt-in rather than opt-out - either way, everything should be in local storage

as for features, i'm somewhat of a minimalist - if it were me, and if i were competent in JS, i'd likely dump the Milkdown dep and convert to MD with some RegEx and while the Dockview dep is nice, i might just provide some prefab templates or something, but don't take that as a bonafide complaint - i'm just glad to see there's something out there that can replace Mark-It

btw, you might want to add a link to your AMO page on your readme.md

**Comment by muerwre** [comment]
Thanks, I'll think about that. Suggesting enabling sync on init is a good idea.
